export const list = {
  data: [
    {
      id: 4,
      title: 'Blue shirt dksfldksl',
      price: '1.00',
      description:
        'The color could be slightly different between on the screen and in practice. / Please note that body builds vary by person, therefore, detailed size information should be reviewed below on the product description.',
      category2: 'Man',
      image: '/assets/img/ali-pazani-fCe-52iIZIM-unsplash.jpg',
      stock: 9,
      created_at: '2023-02-21T10:50:24.000Z',
      active: 1,
      material: 'material default',
      size_guide: 'size guide default',
      info: 'info default',
      color: 'White',
      size: 'L,XL,32',
      colors: ['White'],
      sizes: ['L', 'XL', '32'],
    },
    {
      id: 5,
      title: 'THE NAME',
      price: '695.00',
      description:
        'From our Legends Collection, the Naga was inspired by the mythical water dragon that protects the oceans pearl. Wear facing inward to be bestowed with love and abundance, or outward for protection.',
      category2: 'Man',
      image: '/assets/img/kevin-laminto-osLOXQc_Hpw-unsplash.jpg',
      stock: 8,
      created_at: '2023-02-21T10:50:24.000Z',
      active: 0,
      material: 'material default',
      size_guide: 'size guide default',
      info: 'info default',
      color: 'White,Gray,Black',
      size: '32,34,36',
      colors: ['White', 'Gray', 'Black'],
      sizes: ['32', '34', '36'],
    },
    {
      id: 6,
      title: 'jgjhgjhgj',
      price: '168.00',
      description:
        'Satisfaction Guaranteed. Return or exchange any order within 30 days.Designed and sold by Hafeez Center in the United States. Satisfaction Guaranteed. Return or exchange any order within 30 days.',
      category2: 'Man',
      image: '/assets/img/kevin-laminto-hjAkD8o2rmg-unsplash.jpg',
      stock: 6,
      created_at: '2023-02-21T10:50:24.000Z',
      active: 1,
      material: 'material default',
      size_guide: 'size guide default',
      info: 'info default',
      color: 'White,Gray,Black',
      size: '32,34,36',
      colors: ['White', 'Gray', 'Black'],
      sizes: ['32', '34', '36'],
    },
    {
      id: 7,
      title: 'White Gold Plated Princess',
      price: '9.99',
      description:
        'Classic Created Wedding Engagement Solitaire Diamond Promise Ring for Her. Gifts to spoil your love more for Engagement, Wedding, Anniversary, Valentines Day...',
      category2: 'Man',
      image: '/assets/img/anomaly-WWesmHEgXDs-unsplash.jpg',
      stock: 3,
      created_at: '2023-02-21T10:50:24.000Z',
      active: 1,
      material: 'material default',
      size_guide: 'size guide default',
      info: 'info default',
      color: 'White,Gray,Black',
      size: '32,34,36',
      colors: ['White', 'Gray', 'Black'],
      sizes: ['32', '34', '36'],
    },
    {
      id: 8,
      title: 'Pierced Owl Rose Gold Plated Stainless Steel Double',
      price: '10.99',
      description:
        'Rose Gold Plated Double Flared Tunnel Plug Earrings. Made of 316L Stainless Steel',
      category2: 'Man',
      image: '/assets/img/force-majeure-GGPq78xM8T0-unsplash.jpg',
      stock: 33,
      created_at: '2023-02-21T10:50:24.000Z',
      active: 1,
      material: 'material default',
      size_guide: 'size guide default',
      info: 'info default',
      color: 'Green',
      size: '32,34,36',
      colors: ['Green'],
      sizes: ['32', '34', '36'],
    },
    {
      id: 9,
      title: 'WD 2TB Elements Portable External Hard Drive - USB 3.0 ',
      price: '64.00',
      description:
        'USB 3.0 and USB 2.0 Compatibility Fast data transfers Improve PC Performance High Capacity; Compatibility Formatted NTFS for Windows 10, Windows 8.1, Windows 7; Reformatting may be required for other operating systems; Compatibility may vary depending on user’s hardware configuration and operating system',
      category2: 'Man',
      image: '/assets/img/sven-ciupka-x8Vg7Up6TUc-unsplash.jpg',
      stock: 5,
      created_at: '2023-02-21T10:50:24.000Z',
      active: 1,
      material: 'material default',
      size_guide: 'size guide default',
      info: 'info default',
      color: 'Brown',
      size: '32,34,36',
      colors: ['Brown'],
      sizes: ['32', '34', '36'],
    },
    {
      id: 10,
      title: 'SanDisk SSD PLUS 1TB Internal SSD - SATA III 6 Gb/s',
      price: '109.00',
      description:
        'Easy upgrade for faster boot up, shutdown, application load and response (As compared to 5400 RPM SATA 2.5” hard drive; Based on published specifications and internal benchmarking tests using PCMark vantage scores) Boosts burst write performance, making it ideal for typical PC workloads The perfect balance of performance and reliability Read/write speeds of up to 535MB/s/450MB/s (Based on internal testing; Performance may vary depending upon drive capacity, host device, OS and application.)',
      category2: 'Man',
      image: '/assets/img/force-majeure-keakjB6qkXs-unsplash.jpg',
      stock: 3,
      created_at: '2023-02-21T10:50:24.000Z',
      active: 1,
      material: 'material default',
      size_guide: 'size guide default',
      info: 'info default',
      color: 'Yellow',
      size: '38,40,42,44',
      colors: ['Yellow'],
      sizes: ['38', '40', '42', '44'],
    },
    {
      id: 11,
      title:
        'Silicon Power 256GB SSD 3D NAND A55 SLC Cache Performance Boost SATA III 2.5',
      price: '109.00',
      description:
        '3D NAND flash are applied to deliver high transfer speeds Remarkable transfer speeds that enable faster bootup and improved overall system performance. The advanced SLC Cache Technology allows performance boost and longer lifespan 7mm slim design suitable for Ultrabooks and Ultra-slim notebooks. Supports TRIM command, Garbage Collection technology, RAID, and ECC (Error Checking & Correction) to provide the optimized performance and enhanced reliability.',
      category2: 'Accessories',
      image: '/assets/img/kevin-laminto-PNvTKa_nqa4-unsplash.jpg',
      stock: 1,
      created_at: '2023-02-21T10:50:24.000Z',
      active: 1,
      material: 'material default',
      size_guide: 'size guide default',
      info: 'info default',
      color: 'Blue',
      size: '38,40,42,44',
      colors: ['Blue'],
      sizes: ['38', '40', '42', '44'],
    },
    {
      id: 12,
      title:
        'WD 4TB Gaming Drive Works with Playstation 4 Portable External Hard Drive',
      price: '114.00',
      description:
        'Expand your PS4 gaming experience, Play anywhere Fast and easy, setup Sleek design with high capacity, 3-year manufacturers limited warranty',
      category2: 'Accessories',
      image: '/assets/img/dom-hill-nimElTcTNyY-unsplash.jpg',
      stock: 3,
      created_at: '2023-02-21T10:50:24.000Z',
      active: 1,
      material: 'material default',
      size_guide: 'size guide default',
      info: 'info default',
      color: 'Black',
      size: '38,40,42,44',
      colors: ['Black'],
      sizes: ['38', '40', '42', '44'],
    },
    {
      id: 13,
      title: 'Acer SB220Q bi 21.5 inches Full HD (1920 x 1080) IPS Ultra-Thin',
      price: '599.00',
      description:
        '21. 5 inches Full HD (1920 x 1080) widescreen IPS display And Radeon free Sync technology. No compatibility for VESA Mount Refresh Rate: 75Hz - Using HDMI port Zero-frame design | ultra-thin | 4ms response time | IPS panel Aspect ratio - 16: 9. Color Supported - 16. 7 million colors. Brightness - 250 nit Tilt angle -5 degree to 15 degree. Horizontal viewing angle-178 degree. Vertical viewing angle-178 degree 75 hertz',
      category2: 'Accessories',
      image: '/assets/img/force-majeure-3qdamQEaW-8-unsplash.jpg',
      stock: 0,
      created_at: '2023-02-21T10:50:24.000Z',
      active: 1,
      material: 'material default',
      size_guide: 'size guide default',
      info: 'info default',
      color: 'Gray',
      size: '38,40,42,44',
      colors: ['Gray'],
      sizes: ['38', '40', '42', '44'],
    },
    {
      id: 14,
      title:
        'Samsung 49-Inch CHG90 144Hz Curved Gaming Monitor (LC49HG90DMNXZA) – Super Ultrawide Screen QLED ',
      price: '999.99',
      description:
        '49 INCH SUPER ULTRAWIDE 32:9 CURVED GAMING MONITOR with dual 27 inch screen side by side QUANTUM DOT (QLED) TECHNOLOGY, HDR support and factory calibration provides stunningly realistic and accurate color and contrast 144HZ HIGH REFRESH RATE and 1ms ultra fast response time work to eliminate motion blur, ghosting, and reduce input lag',
      category2: 'Woman',
      image: '/assets/img/kevin-laminto-saF4-j_NiHc-unsplash.jpg',
      stock: 5,
      created_at: '2023-02-21T10:50:24.000Z',
      active: 1,
      material: 'material default',
      size_guide: 'size guide default',
      info: 'info default',
      color: 'Black',
      size: '38,40,42,44',
      colors: ['Black'],
      sizes: ['38', '40', '42', '44'],
    },
    {
      id: 15,
      title: 'BIYLACLESEN Womens 3-in-1 Snowboard Jacket Winter Coats',
      price: '56.99',
      description:
        'Note:The Jackets is US standard size, Please choose size as your usual wear Material: 100% Polyester; Detachable Liner Fabric: Warm Fleece. Detachable Functional Liner: Skin Friendly, Lightweigt and Warm.Stand Collar Liner jacket, keep you warm in cold weather. Zippered Pockets: 2 Zippered Hand Pockets, 2 Zippered Pockets on Chest (enough to keep cards or keys)and 1 Hidden Pocket Inside.Zippered Hand Pockets and Hidden Pocket keep your things secure. Humanized Design: Adjustable and Detachable Hood and Adjustable cuff to prevent the wind and water,for a comfortable fit. 3 in 1 Detachable Design provide more convenience, you can separate the coat and inner as needed, or wear it together. It is suitable for different season and help you adapt to different climates',
      category2: 'Woman',
      image: '/assets/img/ellie-ellien-e3JqeYbTr30-unsplash.jpg',
      stock: 5,
      created_at: '2023-02-21T10:50:24.000Z',
      active: 1,
      material: 'material default',
      size_guide: 'size guide default',
      info: 'info default',
      color: 'Black',
      size: '38,40,42,44',
      colors: ['Black'],
      sizes: ['38', '40', '42', '44'],
    },
    {
      id: 16,
      title:
        'Lock and Love Womens Removable Hooded Faux Leather Moto Biker Jacket',
      price: '29.95',
      description:
        '100% POLYURETHANE(shell) 100% POLYESTER(lining) 75% POLYESTER 25% COTTON (SWEATER), Faux leather material for style and comfort / 2 pockets of front, 2-For-One Hooded denim style faux leather jacket, Button detail on waist / Detail stitching at sides, HAND WASH ONLY / DO NOT BLEACH / LINE DRY / DO NOT IRON',
      category2: 'Woman',
      image: '/assets/img/kevin-laminto-PNvTKa_nqa4-unsplash.jpg',
      stock: 3,
      created_at: '2023-02-21T10:50:24.000Z',
      active: 1,
      material: 'material default',
      size_guide: 'size guide default',
      info: 'info default',
      color: 'Black',
      size: '38,40,42,44',
      colors: ['Black'],
      sizes: ['38', '40', '42', '44'],
    },
    {
      id: 17,
      title: 'Rain Jacket Women Windbreaker Striped Climbing Raincoats',
      price: '39.99',
      description:
        'Lightweight perfet for trip or casual wear---Long sleeve with hooded, adjustable drawstring waist design. Button and zipper front closure raincoat, fully stripes Lined and The Raincoat has 2 side pockets are a good size to hold all kinds of things, it covers the hips, and the hood is generous but doesnt overdo it.Attached Cotton Lined Hood with Adjustable Drawstrings give it a real styled look.',
      category2: 'Woman',
      image: '/assets/img/leonard-F-eCGq7BpaE-unsplash.jpg',
      stock: 5,
      created_at: '2023-02-21T10:50:24.000Z',
      active: 1,
      material: 'material default',
      size_guide: 'size guide default',
      info: 'info default',
      color: 'Black',
      size: 'XS,S,M',
      colors: ['Black'],
      sizes: ['XS', 'S', 'M'],
    },
    {
      id: 18,
      title: 'MBJ Womens Solid Short Sleeve Boat Neck V ',
      price: '9.85',
      description:
        '95% RAYON 5% SPANDEX, Made in USA or Imported, Do Not Bleach, Lightweight fabric with great stretch for comfort, Ribbed on sleeves and neckline / Double stitching on bottom hem',
      category2: 'Woman',
      image: '/assets/img/ellie-ellien-RHxEwq2QD3w-unsplash.jpg',
      stock: 12,
      created_at: '2023-02-21T10:50:24.000Z',
      active: 1,
      material: 'material default',
      size_guide: 'size guide default',
      info: 'info default',
      color: 'Black',
      size: 'XS,S,M',
      colors: ['Black'],
      sizes: ['XS', 'S', 'M'],
    },
    {
      id: 19,
      title: 'Opna Womens Short Sleeve Moisture',
      price: '7.95',
      description:
        '100% Polyester, Machine wash, 100% cationic polyester interlock, Machine Wash & Pre Shrunk for a Great Fit, Lightweight, roomy and highly breathable with moisture wicking fabric which helps to keep moisture away, Soft Lightweight Fabric with comfortable V-neck collar and a slimmer fit, delivers a sleek, more feminine silhouette and Added Comfort',
      category2: 'Accessories',
      image: '/assets/img/zahir-namane-TjUJJACTav4-unsplash.jpg\r\n',
      stock: 8,
      created_at: '2023-02-21T10:50:24.000Z',
      active: 1,
      material: 'material default',
      size_guide: 'size guide default',
      info: 'info default',
      color: 'Black',
      size: 'L,XL',
      colors: ['Black'],
      sizes: ['L', 'XL'],
    },
    {
      id: 20,
      title: 'DANVOUY Womens T Shirt Casual Cotton Short',
      price: '12.99',
      description:
        '95%Cotton,5%Spandex, Features: Casual, Short Sleeve, Letter Print,V-Neck,Fashion Tees, The fabric is soft and has some stretch., Occasion: Casual/Office/Beach/School/Home/Street. Season: Spring,Summer,Autumn,Winter.',
      category2: 'Accessories',
      image: '/assets/img/force-majeure-GGPq78xM8T0-unsplash.jpg',
      stock: 8,
      created_at: '2023-02-21T10:50:24.000Z',
      active: 1,
      material: 'material default',
      size_guide: 'size guide default',
      info: 'info default',
      color: 'Black',
      size: 'One Size',
      colors: ['Black'],
      sizes: ['One Size'],
    },
    {
      id: 23,
      title: 'testar',
      price: '5.00',
      description: 'testar',
      category2: '',
      image: 'testar',
      stock: 5,
      created_at: '2023-03-06T19:20:17.000Z',
      active: 1,
      material: 'testar',
      size_guide: 'testar',
      info: 'testar',
      color: '',
      size: '',
      colors: [''],
      sizes: [''],
    },
    {
      id: 24,
      title: 'testar',
      price: '5.00',
      description: 'testar',
      category2: '',
      image: 'testar',
      stock: 5,
      created_at: '2023-03-06T19:20:30.000Z',
      active: 1,
      material: 'testar',
      size_guide: 'testar',
      info: 'testar',
      color: '',
      size: '',
      colors: [''],
      sizes: [''],
    },
    {
      id: 25,
      title: 'testar',
      price: '5.00',
      description: 'testar',
      category2: '',
      image: 'testar',
      stock: 5,
      created_at: '2023-03-06T19:20:44.000Z',
      active: 1,
      material: 'testar',
      size_guide: 'testar',
      info: 'testar',
      color: '',
      size: '',
      colors: [''],
      sizes: [''],
    },
    {
      id: 26,
      title: 'testar',
      price: '5.00',
      description: 'testar',
      category2: '',
      image: 'testar',
      stock: 5,
      created_at: '2023-03-06T19:21:17.000Z',
      active: 1,
      material: 'testar',
      size_guide: 'testar',
      info: 'testar',
      color: '',
      size: '',
      colors: [''],
      sizes: [''],
    },
    {
      id: 27,
      title: 'testar',
      price: '5.00',
      description: 'testar',
      category2: '',
      image: 'testar',
      stock: 5,
      created_at: '2023-03-06T19:21:42.000Z',
      active: 1,
      material: 'testar',
      size_guide: 'testar',
      info: 'testar',
      color: '',
      size: '',
      colors: [''],
      sizes: [''],
    },
    {
      id: 28,
      title: '',
      price: '0.00',
      description: '',
      category2: '',
      image: '/assets/product-img/example.jpg',
      stock: null,
      created_at: '2023-03-09T14:53:40.000Z',
      active: 1,
      material: 'material default',
      size_guide: 'size guide default',
      info: 'info default',
      color: null,
      size: 'One Size',
      colors: [],
      sizes: ['One Size'],
    },
    {
      id: 29,
      title: 'ads',
      price: '453.00',
      description: 'asdag',
      category2: 'Accessories',
      image: 'null',
      stock: 544,
      created_at: '2023-03-09T14:59:25.000Z',
      active: 0,
      material: 'fgh',
      size_guide: 'qeR ',
      info: 'GDS',
      color: 'White',
      size: 'XS',
      colors: ['White'],
      sizes: ['XS'],
    },
    {
      id: 30,
      title: 'SAGA',
      price: '345.00',
      description: 'kjölkjöl',
      category2: 'Woman',
      image: 'null',
      stock: 345,
      created_at: '2023-03-09T15:01:29.000Z',
      active: 0,
      material: 'sdgsg',
      size_guide: 'gsdsgd',
      info: 'sgdsgd',
      color: 'White',
      size: 'XS',
      colors: ['White'],
      sizes: ['XS'],
    },
  ],
  meta: { page: 1 },
}
